version: "3.9"

services:
  migration-cli:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      MIGRATION_MONGODB_URI: ${MIGRATION_MONGODB_URI}
      MIGRATION_DEFAULT_DB: ${MIGRATION_DEFAULT_DB}
      MIGRATION_DEFAULT_COLLECTION: ${MIGRATION_DEFAULT_COLLECTION}
    depends_on:
      - mongodb
    networks:
      - migration
    volumes:
      - ../data:/app/data:ro
    command: ["--help"]

networks:
  migration:
    name: ${COMPOSE_PROJECT_NAME:-migration}_network